name: Jessie Millward
favicon: null
layout_spectrum: 0.10013951151631773
typography_spectrum: 0.5020187110640109
title: Jessie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d6c5ae'
    - '#78523f'
    - '#9b7961'
    - '#43382e'
  brandStrength: 0.34285522787831724
  lightness: 0.7187794225756079
  saturation: 0.4319340616930276
  rhythmicContrast: 0.9054116236511618
purpose: []
