name: Jessie Millward
favicon: null
layout_spectrum: 0.10013951151631773
typography_spectrum: 0.5020187110640109
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.34285522787831724
  lightness: 0.7187794225756079
  saturation: 0.4319340616930276
  rhythmicContrast: 0.9054116236511618
purpose: []
